//*******************************************************************************
// Localhost
//*******************************************************************************
### Root
GET http://localhost:3000/ HTTP/1.1

### Get All Contacts
GET http://localhost:3000/contacts HTTP/1.1

### Get Contacts By ID
GET http://localhost:3000/contacts/6515e3a1b344514c3e84b7af HTTP/1.1

### Create Contact
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "email": "john@smith.com",
    "favoriteColor": "purple",
    "birthday": "2000-01-1"
}

### Update Contact
PUT http://localhost:3000/contacts/6515fc3b9601ec8b7fda2002 HTTP/1.1
content-type: application/json

{
    "firstName": "Bill"
}

### Delete Contact
DELETE http://localhost:3000/contacts/6515eeed93331bc77433958f HTTP/1.1

//*******************************************************************************
// Production
//*******************************************************************************
### Root
GET https://cse341-b19z.onrender.com/ HTTP/1.1

### Get All Contacts
GET https://cse341-b19z.onrender.com/contacts HTTP/1.1

### Get Contacts By ID
GET https://cse341-b19z.onrender.com/contacts/651606a28db757354fbf2f3b HTTP/1.1

### Create Contact
POST https://cse341-b19z.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Bat",
    "lastName": "Man",
    "email": "bat@man.com",
    "favoriteColor": "black",
    "birthday": "2000-01-1"
}

### Update Contact
PUT https://cse341-b19z.onrender.com/contacts/651606a28db757354fbf2f3b HTTP/1.1
content-type: application/json

{
    "firstName": "Bruce",
    "lastName": "Wayne"
}

### Delete Contact
DELETE https://cse341-b19z.onrender.com/contacts/651606a28db757354fbf2f3b HTTP/1.1