//*******************************************************************************
// Localhost
//*******************************************************************************
### Root
GET http://localhost:3000/

//*******************************************************************************
// Production
//*******************************************************************************
### Root
GET https://cse341-b19z.onrender.com